INSERT INTO GENDER_DTLS VALUES(1,'Male');
INSERT INTO GENDER_DTLS VALUES(2,'Fe-Male');
INSERT INTO COURSE_DTLS VALUES(101,'Java');
INSERT INTO COURSE_DTLS VALUES(102,'Python');
INSERT INTO COURSE_DTLS VALUES(103,'Angular 10');
INSERT INTO COURSE_TIMINGS VALUES(201,'Morning');
INSERT INTO COURSE_TIMINGS VALUES(202,'Afternoon');
INSERT INTO COURSE_TIMINGS VALUES(203,'Evening');
